### ISSUE TITLE
Issue with 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by touala** [google/best#5]
Hello,

Thanks for sharing your work, the tool looks great. I have the following issue on a MacBook Air M2. I've little experience with `rust` so I can't diagnose further. Could be coming from M2 incompatibility or my command/input files...

```sh
$ target/release/best --threads 1 ~/Desktop/mappings.bam ~/References/reference.fa ~/Desktop/best_test
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-core-0.8.0/src/position/sequence_index.rs:42:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-core-0.8.0/src/position/sequence_index.rs:42:10
```

```sh
$ export RUST_BACKTRACE=full
$ target/release/best --threads 1 ~/Desktop/mappings.bam ~/References/reference.fa ~/Desktop/best_test
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-core-0.8.0/src/position/sequence_index.rs:42:10
stack backtrace:
   0:        0x102f8d9e4 - std::backtrace_rs::backtrace::libunwind::trace::hbe97f4303076f99a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102f8d9e4 - std::backtrace_rs::backtrace::trace_unsynchronized::hb462a91ac605b16b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102f8d9e4 - std::sys_common::backtrace::_print_fmt::h555c176cf2344151
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x102f8d9e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84d5e26d26c914d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x102fa5538 - core::fmt::write::h07c7e4739f78f3b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:        0x102f8b104 - std::io::Write::write_fmt::h4a3c5f094ffc65e8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:        0x102f8d7f8 - std::sys_common::backtrace::_print::h03a1c9ac6001091a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x102f8d7f8 - std::sys_common::backtrace::print::h6fc2cc8be2392a8e
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x102f8f038 - std::panicking::default_hook::{{closure}}::h3bb44ba6ff437e23
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:        0x102f8ed90 - std::panicking::default_hook::h92c6668a1a98ae8c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:        0x102f8f674 - std::panicking::rust_panic_with_hook::h9b8acc949e1fb807
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:        0x102f8f484 - std::panicking::begin_panic_handler::{{closure}}::hfc38b2cc56e3623c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:        0x102f8de4c - std::sys_common::backtrace::__rust_end_short_backtrace::hbafd151207fc448f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x102f8f1d8 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:        0x102fb6df4 - core::panicking::panic_fmt::h8c7f3d540a75578f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:        0x102fb6ed8 - core::panicking::panic_bounds_check::h7a933820625ca023
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:151:5
  16:        0x102ee16f8 - best::stats::AlnStats::from_record::h891032a21f46ba53
  17:        0x102f0ada4 - <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume::hc5fa0a0571f7ebb2
  18:        0x102ee3db0 - <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with::h68648791be95e8e1
  19:        0x102f028d0 - rayon::iter::plumbing::bridge_unindexed_producer_consumer::h0a6c957847b1d4da
  20:        0x102f03800 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha25a46a5a0aba9a6
  21:        0x102f09d6c - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h9a3407efc1e3497d
  22:        0x102fb0bb8 - rayon_core::registry::WorkerThread::wait_until_cold::h693aa9682dd39976
  23:        0x102f2a340 - rayon_core::registry::ThreadBuilder::run::h5448aedadc297cad
  24:        0x102f28b40 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f8e6945afdf1c1f
  25:        0x102f2d174 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he294d1cfe1066b57
  26:        0x102f9170c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3fa970363cd53bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  27:        0x102f9170c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59336ad52adbfea0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  28:        0x102f9170c - std::sys::unix::thread::Thread::new::thread_start::h6a9bbfaea09dc826
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  29:        0x1a798826c - __pthread_deallocate
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-core-0.8.0/src/position/sequence_index.rs:42:10
stack backtrace:
   0:        0x102f8d9e4 - std::backtrace_rs::backtrace::libunwind::trace::hbe97f4303076f99a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102f8d9e4 - std::backtrace_rs::backtrace::trace_unsynchronized::hb462a91ac605b16b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102f8d9e4 - std::sys_common::backtrace::_print_fmt::h555c176cf2344151
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x102f8d9e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84d5e26d26c914d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x102fa5538 - core::fmt::write::h07c7e4739f78f3b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:        0x102f8b104 - std::io::Write::write_fmt::h4a3c5f094ffc65e8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:        0x102f8d7f8 - std::sys_common::backtrace::_print::h03a1c9ac6001091a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x102f8d7f8 - std::sys_common::backtrace::print::h6fc2cc8be2392a8e
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x102f8f038 - std::panicking::default_hook::{{closure}}::h3bb44ba6ff437e23
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:        0x102f8ed90 - std::panicking::default_hook::h92c6668a1a98ae8c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:        0x102f8f674 - std::panicking::rust_panic_with_hook::h9b8acc949e1fb807
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:        0x102f8f484 - std::panicking::begin_panic_handler::{{closure}}::hfc38b2cc56e3623c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:        0x102f8de4c - std::sys_common::backtrace::__rust_end_short_backtrace::hbafd151207fc448f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x102f8f1d8 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:        0x102fb6df4 - core::panicking::panic_fmt::h8c7f3d540a75578f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:        0x102fb6ed8 - core::panicking::panic_bounds_check::h7a933820625ca023
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:151:5
  16:        0x102ee16f8 - best::stats::AlnStats::from_record::h891032a21f46ba53
  17:        0x102f0ada4 - <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume::hc5fa0a0571f7ebb2
  18:        0x102ee3db0 - <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with::h68648791be95e8e1
  19:        0x102f028d0 - rayon::iter::plumbing::bridge_unindexed_producer_consumer::h0a6c957847b1d4da
  20:        0x102f09fac - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::haac1f5ff8a193dbb
  21:        0x102fb0bb8 - rayon_core::registry::WorkerThread::wait_until_cold::h693aa9682dd39976
  22:        0x102fb1134 - rayon_core::join::join_recover_from_panic::hd9813d47c1f54ca4
  23:        0x102f03904 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha25a46a5a0aba9a6
  24:        0x102f09d6c - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h9a3407efc1e3497d
  25:        0x102fb0bb8 - rayon_core::registry::WorkerThread::wait_until_cold::h693aa9682dd39976
  26:        0x102f2a340 - rayon_core::registry::ThreadBuilder::run::h5448aedadc297cad
  27:        0x102f28b40 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f8e6945afdf1c1f
  28:        0x102f2d174 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he294d1cfe1066b57
  29:        0x102f9170c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3fa970363cd53bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  30:        0x102f9170c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59336ad52adbfea0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  31:        0x102f9170c - std::sys::unix::thread::Thread::new::thread_start::h6a9bbfaea09dc826
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  32:        0x1a798826c - __pthread_deallocate
```

Best,

Alan

**Comment by Daniel-Liu-c0deb0t** [comment]
Seems like either a reference or a read has length 0. When looping over the cigar operations, it's incurring an out of bounds access. Can you try to narrow down to which BAM entry is causing the issue (perhaps with binary search) or double check the references?

**Comment by touala** [comment]
Thanks for the quick response. I've looked at a couple of bam slices but all have an issue. For example, this single read do not work:
```
4bc8edcf-1be6-420a-b0cb-bd63e0028f56	0	chrI	4297	0	60M1I31M1I40M1I36M1D31M1D74M1I6M3D38M3D17M3D88M1I44M1I8M1I60M2D8M1D91M2D6M1D6M2D33M1I33M9I20M1D15M1D6M1I76M2D15M1I17M	*	0	878	CGAAGAACAATGCAATAGCTCTTACAAACCACTACATGACAAGCAACTCATAATTTAAGTAGGATAGCTTGTGATAAATTGAATTTTCTCTGTTTTAGTACTTGCCGAATAGTTACTTGTTAGTTGCAGATGCTTTTTTGATGACAAAGTTATCAATCTCAATAATAAACTTTTAGGCTTTCAGGTTTAATCTTTCTTTGAGGTGTATTAATCTTCATACAAATATTTGATTCATTATTCGTTTTACTGTTACATTAGACCTACTCATTACATGGAAGTAACAGGTTTCTCAAACGCTTCATAGCATGATTTGATGTAGTAAAAAAGGCAGAGTTTCAAAAAATTGTTAATCGACAAAGTTAATATTATGGTGGTAGTATCTCAAATATCTGAATAACCAGATCGTACATCTCTGATAAACAATCTTTTGCCACTACTTTATCCTTTTAAATTGTGTTGAGTGCTTAAGTCCTTTGCAAGAATTTTGCCGGATTTAAAATTTGTGAACCCGACCTTATCGAGAAATGATGTGCTAATTTTTAGGTCGACCTTCTGCCGCTTACTGGGTTGATTATCTTGTGCTTTCTTAGTATCTATCACAAAAGAGACAAAATCGTTGATAAAAAGTGCATCAACATTCAGCCAAAAATGCATCATAAAGACATGTTATTCAAGAGCCACGACTGGTCTTTAATTTATCTTTTATAAAAAATCCTTGTTTTGCTGATTCTACTGACAGGATGGAATGATATTAAATATACATTTGCATTTTTTTTTTTTTTCTGTATTGAAGATTTGTATATGAAAGATGTTTATACATCAAATGCTTTGAATAAAGCCATCTTGTTCAATTTCATGCCACTCCTTCACCGTTTTCT	*	NM:i:42
```

I can visualize the read with IGV and the reference. Nothing looks off.

**Comment by Daniel-Liu-c0deb0t** [comment]
Oh it's probably because the reads don't have corresponding quality scores. Quality scores are used in many of the analyses that `best` does. I think a good way to address this is to give a better error message if it is missing.

**Comment by touala** [comment]
You're right, using reads with basecall quality score works fine. FYI, the score-less mapping is obtained using `megalodon --outputs mappings`. I'm not sure if it can output it with non-default options...

On the same topic, you might want to change the error message for when the mapping do not match the reference (e.g. `'index out of bounds: the len is 230218 but the index is 230218'`), even if this is a clearer message already.

Thank you for the quick diagnosis.
